### ISSUE TITLE
ERROR while processing rebar_abort

### ISSUE THREAD

**Issue by amelyec** [PowerMeMobile/smppsink#2]
I got this error on CentOS 7, please advise

ERROR: Dependency dir /var/code/smppsink/deps/entop failed application validation with reason:
{version_mismatch,{"/var/code/smppsink/deps/entop/src/entop.app.src",
                   {expected,"0.0.1"},
                   {has,"0.3.1"}}}.
ERROR: 'get-deps' failed while processing /var/code/smppsink: rebar_abort
make: *** [get-deps] Error 1

**Comment by ten0s** [comment]
You can safely remove the below entries from rebar.config

 {entop, "0.0.1", {git, "https://github.com/mazenharake/entop.git", {branch, "master"}}},
 {eper, ".*", {git, "https://github.com/massemanet/eper.git", {tag, "0.92.0"}}},

Then remove the deps dir and try again.

Which Erlang version do you use?

**Comment by amelyec** [comment]
My Erlang Version

Package erlang-R16B-03.18.el7.x86_64 already installed and latest version

**Comment by amelyec** [comment]
I have removed lines from rebar.config and deps dir, got the error below

ERROR: generate failed while processing /home/user/smpp/smppsink/rel: {'EXIT',{{badmatch,{error,"entop: Missing application directory."}},
         [{rebar_reltool,generate,2,
                         [{file,"src/rebar_reltool.erl"},{line,53}]},
          {rebar_core,run_modules,4,[{file,"src/rebar_core.erl"},{line,445}]},
          {rebar_core,execute,5,[{file,"src/rebar_core.erl"},{line,371}]},
          {rebar_core,process_dir1,6,[{file,"src/rebar_core.erl"},{line,235}]},
          {rebar_core,process_each,5,[{file,"src/rebar_core.erl"},{line,305}]},
          {rebar_core,process_dir1,6,[{file,"src/rebar_core.erl"},{line,211}]},
          {rebar_core,process_commands,2,
                      [{file,"src/rebar_core.erl"},{line,90}]},
          {rebar,main,1,[{file,"src/rebar.erl"},{line,58}]}]}}
make: *** [generate] Error 1

**Comment by ten0s** [comment]
Also remove the below from rel/reltool.config

    {app, entop, [{incl_cond, include}]},
    {app, eper, [{incl_cond, include}]},

Then remove the deps dir and try again.

**Comment by amelyec** [comment]
Thank you very much, it works.
